# 学校信息自动填报工作流
name: 学校信息自动填报

on:
  issues:
    types: [labeled]

# 设置必要的权限
permissions:
  contents: write
  issues: read
  pull-requests: write

jobs:
  append-school-info:
    runs-on: ubuntu-latest
    if: github.event.label.name == '审核通过' && contains(github.event.issue.labels.*.name, '学校信息填报')
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 追加学校信息到表格
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');
            const filePath = 'docs/school/index.md';
            const issue = context.payload.issue;
            
            // 验证issue是否存在
            if (!issue || !issue.body) {
              core.setFailed('Issue内容为空');
              return;
            }
            
            // 解析学校信息字段
            const location = issue.body.match(/school_location[:：]\s*(.+)/)?.[1]?.trim() || '';
            const type = issue.body.match(/school_type[:：]\s*(.+)/)?.[1]?.trim() || '';
            const name = issue.body.match(/school_name[:：]\s*(.+)/)?.[1]?.trim() || '';
            
            // 验证必要字段
            if (!location || !type || !name) {
              core.setFailed('缺少必要字段：school_location、school_type、school_name');
              return;
            }
            
            // 验证文件是否存在
            if (!fs.existsSync(filePath)) {
              core.setFailed(`文件不存在: ${filePath}`);
              return;
            }
            
            try {
              let content = fs.readFileSync(filePath, 'utf8');
              
              // 检查是否已存在相同学校
              if (content.includes(`[${name}]`)) {
                core.setOutput('result', '学校已存在，跳过添加');
                return;
              }
              
              // 找到表格最后一行插入
              const lastRowIdx = content.lastIndexOf('\n|');
              const insertIdx = lastRowIdx === -1 ? content.length : lastRowIdx;
              const newRow = `| ${location} | ${type} | [${name}](/school/list/${name}) |\n`;
              
              // 插入到表格末尾
              content = content.slice(0, insertIdx) + newRow + content.slice(insertIdx);
              fs.writeFileSync(filePath, content, 'utf8');
              
              core.setOutput('result', '学校信息添加成功');
            } catch (error) {
              core.setFailed(`处理文件时出错: ${error.message}`);
            }

      - name: 提交更改
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '自动追加学校信息到表格'
          file_pattern: 'docs/school/index.md'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'